---
# SPDX-FileCopyrightText: 2024 SAP edge team
# SPDX-FileContributor: Kirill Satarin (@kksat)
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0
# This CloudFormation template provisions Route 53 A-records for a ROSA cluster.
# It maps api, *.apps and console endpoints under your custom domain to a single
# IPv4 address (typically the cluster's external load balancer).

AWSTemplateFormatVersion: '2010-09-09'
Description: 'ROSA Domain Records - Route53 DNS records for custom domains'

Parameters:
  HostedZoneName:
    Type: String
    Description: The name of the Route53 hosted zone where records will be created
    Default: saponrhel.org

  RecordName:
    Type: String
    Description: The DNS record name (subdomain) to be created
    Default: api

  ClusterName:
    Type: String
    Description: ROSA cluster name for record naming
    Default: sapeic

  IPv4Address:
    Type: String
    Description: IPv4 address to be associated with the A record
    AllowedPattern: '^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'

  TTL:
    Type: Number
    Description: DNS record time to live (TTL) in seconds
    Default: 3600
    MinValue: 60
    MaxValue: 86400

Resources:
  # API Record
  APIRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostedZoneName}."
      Name: !Sub "api.${ClusterName}.${HostedZoneName}."
      Type: A
      TTL: !Ref TTL
      ResourceRecords:
        - !Ref IPv4Address

  # Apps wildcard record
  AppsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostedZoneName}."
      Name: !Sub "*.apps.${ClusterName}.${HostedZoneName}."
      Type: A
      TTL: !Ref TTL
      ResourceRecords:
        - !Ref IPv4Address

  # Console record
  ConsoleRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostedZoneName}."
      Name: !Sub "console-openshift-console.apps.${ClusterName}.${HostedZoneName}."
      Type: A
      TTL: !Ref TTL
      ResourceRecords:
        - !Ref IPv4Address

Outputs:
  APIEndpoint:
    Description: API endpoint DNS name
    Value: !Sub "api.${ClusterName}.${HostedZoneName}"
    Export:
      Name: !Sub "${AWS::StackName}-APIEndpoint"

  AppsWildcard:
    Description: Apps wildcard DNS name
    Value: !Sub "*.apps.${ClusterName}.${HostedZoneName}"
    Export:
      Name: !Sub "${AWS::StackName}-AppsWildcard"

  ConsoleEndpoint:
    Description: Console endpoint DNS name
    Value: !Sub "console-openshift-console.apps.${ClusterName}.${HostedZoneName}"
    Export:
      Name: !Sub "${AWS::StackName}-ConsoleEndpoint"

  HostedZone:
    Description: Route53 hosted zone name
    Value: !Ref HostedZoneName
    Export:
      Name: !Sub "${AWS::StackName}-HostedZone"
